CREATE TABLE [dbo].[Products](
	[Id] [BIGINT] IDENTITY(1,1) NOT NULL,
	[Type] [NVARCHAR](50) NOT NULL,
	[Price] [INT] NOT NULL,
	[Quantity] [INT] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO